### ISSUE TITLE
Plus de data sur les villes

### ISSUE THREAD

**Issue by ManUtopiK** [MathRobin/codepostaux#1]
Salut,
j'ai fait un dépôt de base de données en sql regroupant plusieurs données sur toutes les villes de France, ici : https://github.com/ggouv/Villes-de-France
C'est en sql, mais j'ai aussi cette base en json sur mon ordi...

J'ai croisé les données à partir de plusieurs sources. Il y a les données suivantes :
`cp`, `insee`, `article`, `ville`, `libelle`, `region`, `dep`, `lat`, `long`, `habitants30122008`, `densite30122008`

Mais franchement, l'état devrait proposer ces données en mode open data !

**Comment by MathRobin** [comment]
Ah top, ça peut être pratique. Tu exiges quelque chose, une contrepartie ? Ton contenu est sous quelle licence ? On est d'accord que ça devrait être de l'open data

**Comment by MathRobin** [comment]
concernant une partie des données, voilà qui répond à tout débat https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/
