### ISSUE TITLE
Typescript & Angular support

### ISSUE THREAD

**Issue by PaulCordo** [MathRobin/codepostaux#3]
Pour pouvoir utiliser ce module dans un projet Typescript et éviter un parse error de cp.js dû aux clefs des codes postaux débutants par un 0 il faudrait modifier l'objet tel qu'avec une RegEx:
remplacer '(\d{5}) :' par '"$1" :'
Merci pour ce projet !

**Comment by MathRobin** [comment]
Salut, ce projet est désormais déprécié. Je t'invite à regarder plutôt auprès du projet https://github.com/etalab/codes-postaux du merveilleux @etalab

Merci pour la suggestion ceci dit
